ci: clean up and fixes (#5054)
* ci: remove unused helper script

* ci: update CI machine images

Try to fix error a la:

```text
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://docker-images-prod.s3.dualstack.us-east-1.amazonaws.com/registry-v2/docker/registry/v2/blobs/sha256/...": dial tcp 52.216.28.112:443: i/o timeout
```

See https://discuss.circleci.com/t/increased-rate-of-errors-when-pulling-docker-images-on-machine-executor/42094/9