Fix issue preventing build in Windows
Removed nil in return which was stopping the build in Windows. `src\github.com\influxdb\influxdb\tsdb\engine\tsm1\mmap_windows.go:13: too many arguments to return` issue is fixed.