test(models): don't reassign package variable
Prior to this change, `go test -count=2 ./models` would fail like:

--- FAIL: TestMarshal (0.00s)
    points_test.go:37: got:  ,A\ FOO=bar,APPLE=orange,host=serverA,region=uswest
    points_test.go:38: exp:  ,apple=orange,foo=bar,host=serverA,region=uswest
    points_test.go:39: invalid match

because a later test reassigned the package-level variable that
TestMarshal depends on. Don't reassign that variable anymore.

Also cleaned up some whitespace, and moved an init function to the top
of the file for visibility.